source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'DRBrower' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'AXStretchableHeaderTabViewController', '~> 0.2.0'
  pod 'Mantle', '~> 1.5.4'
  pod 'SDWebImage', '~> 3.7.3'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'PYSearch', '~> 0.3.4'
  pod 'CSStickyHeaderFlowLayout', '~> 0.2.11'
  pod 'MZFormSheetPresentationController', '~> 2.4.2'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Colours', '~> 5.13.0'
  pod 'SWTableViewCell', '~> 0.3.7'
  pod 'DZNEmptyDataSet', '~> 1.8.1'
  pod 'Realm', '~> 2.0.4'
  pod 'ShareSDK3'
  pod 'MOBFoundation'
  pod 'ShareSDK3/ShareSDKPlatforms/QQ'
  pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
  pod 'Masonry', '~> 1.0.2'
  pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'
  pod 'Bugly'
end
